name: Build iOS App

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Package
    runs-on: macos-26

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ccache-${{ runner.os }}-${{ github.sha }}
          restore-keys: ccache-${{ runner.os }}-


      - name: Install Dependencies
        run: |
          set -e
          brew install ldid dpkg libarchive cmake ninja ccache

      - name: Cache Theos
        id: cache-theos
        uses: actions/cache@v4
        with:
          path: ~/theos
          key: theos-${{ runner.os }}-v1

      - name: Install Theos
        if: steps.cache-theos.outputs.cache-hit != 'true'
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos


      - name: Setup SDK
        run: |
          mkdir -p ~/theos/sdks
          curl -L https://github.com/theos/sdks/archive/master.tar.gz | tar -xz -C ~/theos/sdks --strip-components=1


      - name: Cache Build Artifacts
        id: cache-artifacts
        uses: actions/cache@v4
        with:
          path: |
            Nyxian/LindChain/LLVM.xcframework
            Nyxian/LindChain/Clang.xcframework
            Nyxian/LindChain/JBSupport/libroot.a
            Nyxian/LindChain/JBSupport/tshelper
          key: build-artifacts-${{ runner.os }}-${{ hashFiles('Makefile', 'LLVM-On-iOS/Makefile', 'libroot/Makefile', 'TrollStore/Makefile') }}

      - name: Setup
        run: |
          set -e
          echo "CCACHE_DIR=~/.ccache" >> $GITHUB_ENV
          echo "THEOS=~/theos" >> $GITHUB_ENV

          echo "PATH=$HOME/theos/bin:$PATH" >> $GITHUB_ENV

      - name: Build Jailed
        timeout-minutes: 1200
        run: |
          set -e
          make jailed
          mkdir build_cmake && cd build_cmake
          cmake -G Ninja ..
          ninja

      - name: Build Rootless
        run: |
          set -e
          make rootless

      - name: Build Roothide
        run: |
          set -e
          make roothide

      - name: Build Rootful
        run: |
          set -e
          make rootful

      - name: Upload Jailed
        uses: actions/upload-artifact@v4
        with:
          name: nyxian.ipa
          path: nyxian.ipa

      - name: Upload Rootless
        uses: actions/upload-artifact@v4
        with:
          name: nyxian_0.9.0_iphoneos-arm64.deb
          path: nyxian_0.9.0_iphoneos-arm64.deb

      - name: Upload Roothide
        uses: actions/upload-artifact@v4
        with:
          name: nyxian_0.9.0_iphoneos-arm64e.deb
          path: nyxian_0.9.0_iphoneos-arm64e.deb

      - name: Upload Rootful
        uses: actions/upload-artifact@v4
        with:
          name: nyxian_0.9.0_iphoneos-arm.deb
          path: nyxian_0.9.0_iphoneos-arm.deb
